stages:
  - test

unit-test:
  image: java:8
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - chmod +x gradlew
    - ./gradlew test
    - cat build/reports/jacoco/test/html/index.html